-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg5Gdye+cIAGUhL5T/
0WtcbKNt4wlnBmXCz6L1czxALTGgCgYIKoZIzj0DAQehRANCAARy9qZhbq6XkFnm
xf7JatfoQKDdjBgu2u2qxpdepzxt/HeG73ZiMbxNuwduu3RPU2d2G7uc5iAXFDV9
YEGL7O+/
-----END PRIVATE KEY-----